# Generated by Django 4.1 on 2023-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bank_delete_bankpersonnal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.CharField(choices=[('6month', '6 MONTHS'), ('12month', '12 MMONTHS'), ('18month', '18 MONTHS'), ('24month', '24 MONTHS'), ('36month', '36 MONTHS')], default='6month', max_length=7),
        ),
    ]
