# Generated by Django 4.2.3 on 2023-07-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_loan_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancustomer',
            name='loandetail',
        ),
        migrations.AddField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.loancustomer'),
            preserve_default=False,
        ),
    ]
