# Generated by Django 4.2.3 on 2023-07-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_bank_provide_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='toal_budget',
            new_name='total_budget',
        ),
    ]
