# Generated by Django 4.2.3 on 2023-07-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_loancustomer_id_alter_loanprovider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loanprovider'),
        ),
    ]
