# Generated by Django 4.2.3 on 2023-07-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_bank_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='minimum_salary',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bank'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.CharField(choices=[('6month', '6 MONTHS'), ('12month', '12 MMONTHS'), ('18month', '18 MONTHS'), ('24month', '24 MONTHS'), ('36month', '36 MONTHS')], default='6month', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
